//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMatrix.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("172.27.102.186")]
        public string DeviceAddress {
            get {
                return ((string)(this["DeviceAddress"]));
            }
            set {
                this["DeviceAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TestDigitalLines {
            get {
                return ((bool)(this["TestDigitalLines"]));
            }
            set {
                this["TestDigitalLines"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Out1_DigitalLine {
            get {
                return ((string)(this["Out1_DigitalLine"]));
            }
            set {
                this["Out1_DigitalLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Out2_DigitalLine {
            get {
                return ((string)(this["Out2_DigitalLine"]));
            }
            set {
                this["Out2_DigitalLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Out3_DigitalLine {
            get {
                return ((string)(this["Out3_DigitalLine"]));
            }
            set {
                this["Out3_DigitalLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string In1_DigitalLine {
            get {
                return ((string)(this["In1_DigitalLine"]));
            }
            set {
                this["In1_DigitalLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string In2_DigitalLine {
            get {
                return ((string)(this["In2_DigitalLine"]));
            }
            set {
                this["In2_DigitalLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TestGoodRead {
            get {
                return ((bool)(this["TestGoodRead"]));
            }
            set {
                this["TestGoodRead"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("*good*")]
        public string GoodRead_pattern {
            get {
                return ((string)(this["GoodRead_pattern"]));
            }
            set {
                this["GoodRead_pattern"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("51236")]
        public string GoodRead_TCPClient_hostPort {
            get {
                return ((string)(this["GoodRead_TCPClient_hostPort"]));
            }
            set {
                this["GoodRead_TCPClient_hostPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GoodRead_TCPServer_hostPort {
            get {
                return ((string)(this["GoodRead_TCPServer_hostPort"]));
            }
            set {
                this["GoodRead_TCPServer_hostPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GoodRead_UDPServer_hostPort {
            get {
                return ((string)(this["GoodRead_UDPServer_hostPort"]));
            }
            set {
                this["GoodRead_UDPServer_hostPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GoodRead_SerialMain_comPort {
            get {
                return ((string)(this["GoodRead_SerialMain_comPort"]));
            }
            set {
                this["GoodRead_SerialMain_comPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GoodRead_SerialAUX_comPort {
            get {
                return ((string)(this["GoodRead_SerialAUX_comPort"]));
            }
            set {
                this["GoodRead_SerialAUX_comPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TestNoRead {
            get {
                return ((bool)(this["TestNoRead"]));
            }
            set {
                this["TestNoRead"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("*noread*")]
        public string NoRead_pattern {
            get {
                return ((string)(this["NoRead_pattern"]));
            }
            set {
                this["NoRead_pattern"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("51236")]
        public string NoRead_TCPClient_hostPort {
            get {
                return ((string)(this["NoRead_TCPClient_hostPort"]));
            }
            set {
                this["NoRead_TCPClient_hostPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NoRead_TCPServer_hostPort {
            get {
                return ((string)(this["NoRead_TCPServer_hostPort"]));
            }
            set {
                this["NoRead_TCPServer_hostPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NoRead_UDPServer_hostPort {
            get {
                return ((string)(this["NoRead_UDPServer_hostPort"]));
            }
            set {
                this["NoRead_UDPServer_hostPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NoRead_SerialMain_comPort {
            get {
                return ((string)(this["NoRead_SerialMain_comPort"]));
            }
            set {
                this["NoRead_SerialMain_comPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NoRead_SerialAUX_comPort {
            get {
                return ((string)(this["NoRead_SerialAUX_comPort"]));
            }
            set {
                this["NoRead_SerialAUX_comPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TestPartialRead {
            get {
                return ((bool)(this["TestPartialRead"]));
            }
            set {
                this["TestPartialRead"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("*partial*")]
        public string PartialRead_pattern {
            get {
                return ((string)(this["PartialRead_pattern"]));
            }
            set {
                this["PartialRead_pattern"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("51236")]
        public string PartialRead_TCPClient_hostPort {
            get {
                return ((string)(this["PartialRead_TCPClient_hostPort"]));
            }
            set {
                this["PartialRead_TCPClient_hostPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PartialRead_TCPServer_hostPort {
            get {
                return ((string)(this["PartialRead_TCPServer_hostPort"]));
            }
            set {
                this["PartialRead_TCPServer_hostPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PartialRead_UDPServer_hostPort {
            get {
                return ((string)(this["PartialRead_UDPServer_hostPort"]));
            }
            set {
                this["PartialRead_UDPServer_hostPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PartialRead_SerialMain_comPort {
            get {
                return ((string)(this["PartialRead_SerialMain_comPort"]));
            }
            set {
                this["PartialRead_SerialMain_comPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PartialRead_SerialAUX_comPort {
            get {
                return ((string)(this["PartialRead_SerialAUX_comPort"]));
            }
            set {
                this["PartialRead_SerialAUX_comPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TestMultipleRead {
            get {
                return ((bool)(this["TestMultipleRead"]));
            }
            set {
                this["TestMultipleRead"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("*multi*")]
        public string MultipleRead_pattern {
            get {
                return ((string)(this["MultipleRead_pattern"]));
            }
            set {
                this["MultipleRead_pattern"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("51236")]
        public string MultipleRead_TCPClient_hostPort {
            get {
                return ((string)(this["MultipleRead_TCPClient_hostPort"]));
            }
            set {
                this["MultipleRead_TCPClient_hostPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MultipleRead_TCPServer_hostPort {
            get {
                return ((string)(this["MultipleRead_TCPServer_hostPort"]));
            }
            set {
                this["MultipleRead_TCPServer_hostPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MultipleRead_UDPServer_hostPort {
            get {
                return ((string)(this["MultipleRead_UDPServer_hostPort"]));
            }
            set {
                this["MultipleRead_UDPServer_hostPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MultipleRead_SerialMain_comPort {
            get {
                return ((string)(this["MultipleRead_SerialMain_comPort"]));
            }
            set {
                this["MultipleRead_SerialMain_comPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MultipleRead_SerialAUX_comPort {
            get {
                return ((string)(this["MultipleRead_SerialAUX_comPort"]));
            }
            set {
                this["MultipleRead_SerialAUX_comPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TestHeartBeat {
            get {
                return ((bool)(this["TestHeartBeat"]));
            }
            set {
                this["TestHeartBeat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("*heart*")]
        public string HeartBeat_pattern {
            get {
                return ((string)(this["HeartBeat_pattern"]));
            }
            set {
                this["HeartBeat_pattern"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("51236")]
        public string HeartBeat_TCPClient_hostPort {
            get {
                return ((string)(this["HeartBeat_TCPClient_hostPort"]));
            }
            set {
                this["HeartBeat_TCPClient_hostPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HeartBeat_TCPServer_hostPort {
            get {
                return ((string)(this["HeartBeat_TCPServer_hostPort"]));
            }
            set {
                this["HeartBeat_TCPServer_hostPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HeartBeat_UDPServer_hostPort {
            get {
                return ((string)(this["HeartBeat_UDPServer_hostPort"]));
            }
            set {
                this["HeartBeat_UDPServer_hostPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HeartBeat_SerialMain_comPort {
            get {
                return ((string)(this["HeartBeat_SerialMain_comPort"]));
            }
            set {
                this["HeartBeat_SerialMain_comPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HeartBeat_SerialAUX_comPort {
            get {
                return ((string)(this["HeartBeat_SerialAUX_comPort"]));
            }
            set {
                this["HeartBeat_SerialAUX_comPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GeneratePhase {
            get {
                return ((bool)(this["GeneratePhase"]));
            }
            set {
                this["GeneratePhase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GeneratePeriodicPhase {
            get {
                return ((bool)(this["GeneratePeriodicPhase"]));
            }
            set {
                this["GeneratePeriodicPhase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GeneratePhaseOnEncoder {
            get {
                return ((bool)(this["GeneratePhaseOnEncoder"]));
            }
            set {
                this["GeneratePhaseOnEncoder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string PhaseOnDuration {
            get {
                return ((string)(this["PhaseOnDuration"]));
            }
            set {
                this["PhaseOnDuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string PhaseOffDuration {
            get {
                return ((string)(this["PhaseOffDuration"]));
            }
            set {
                this["PhaseOffDuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string PhaseOnRandMinDuration {
            get {
                return ((string)(this["PhaseOnRandMinDuration"]));
            }
            set {
                this["PhaseOnRandMinDuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string PhaseOnRandMaxDuration {
            get {
                return ((string)(this["PhaseOnRandMaxDuration"]));
            }
            set {
                this["PhaseOnRandMaxDuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string PhaseOffRandMinDuration {
            get {
                return ((string)(this["PhaseOffRandMinDuration"]));
            }
            set {
                this["PhaseOffRandMinDuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string PhaseOffRandMaxDuration {
            get {
                return ((string)(this["PhaseOffRandMaxDuration"]));
            }
            set {
                this["PhaseOffRandMaxDuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Active High")]
        public string PhaseOnActiveState {
            get {
                return ((string)(this["PhaseOnActiveState"]));
            }
            set {
                this["PhaseOnActiveState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GenerateEncoder {
            get {
                return ((bool)(this["GenerateEncoder"]));
            }
            set {
                this["GenerateEncoder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Frequency")]
        public string EncoderGenerated {
            get {
                return ((string)(this["EncoderGenerated"]));
            }
            set {
                this["EncoderGenerated"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string EncoderFrequency {
            get {
                return ((string)(this["EncoderFrequency"]));
            }
            set {
                this["EncoderFrequency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public string ConveyorSpeed {
            get {
                return ((string)(this["ConveyorSpeed"]));
            }
            set {
                this["ConveyorSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.27")]
        public string EncoderSteps {
            get {
                return ((string)(this["EncoderSteps"]));
            }
            set {
                this["EncoderSteps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GenerateStartStop {
            get {
                return ((bool)(this["GenerateStartStop"]));
            }
            set {
                this["GenerateStartStop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public string StartStopTransition {
            get {
                return ((string)(this["StartStopTransition"]));
            }
            set {
                this["StartStopTransition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public string ConveyorOFFMaxDuration {
            get {
                return ((string)(this["ConveyorOFFMaxDuration"]));
            }
            set {
                this["ConveyorOFFMaxDuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public string ConveyorOFFMinDuration {
            get {
                return ((string)(this["ConveyorOFFMinDuration"]));
            }
            set {
                this["ConveyorOFFMinDuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public string ConveyorONMaxDuration {
            get {
                return ((string)(this["ConveyorONMaxDuration"]));
            }
            set {
                this["ConveyorONMaxDuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public string ConveyorONMinDuration {
            get {
                return ((string)(this["ConveyorONMinDuration"]));
            }
            set {
                this["ConveyorONMinDuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GenerateTrigger {
            get {
                return ((bool)(this["GenerateTrigger"]));
            }
            set {
                this["GenerateTrigger"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string TriggerDuration {
            get {
                return ((string)(this["TriggerDuration"]));
            }
            set {
                this["TriggerDuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public string TriggerPeriod {
            get {
                return ((string)(this["TriggerPeriod"]));
            }
            set {
                this["TriggerPeriod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Active High")]
        public string TriggerActiveState {
            get {
                return ((string)(this["TriggerActiveState"]));
            }
            set {
                this["TriggerActiveState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TriggerOnPhaseOff {
            get {
                return ((bool)(this["TriggerOnPhaseOff"]));
            }
            set {
                this["TriggerOnPhaseOff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PhaseDigitalDevice {
            get {
                return ((string)(this["PhaseDigitalDevice"]));
            }
            set {
                this["PhaseDigitalDevice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PhaseDigitalPort {
            get {
                return ((string)(this["PhaseDigitalPort"]));
            }
            set {
                this["PhaseDigitalPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PhaseDigitalLine {
            get {
                return ((string)(this["PhaseDigitalLine"]));
            }
            set {
                this["PhaseDigitalLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TriggerDigitalDevice {
            get {
                return ((string)(this["TriggerDigitalDevice"]));
            }
            set {
                this["TriggerDigitalDevice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TriggerDigitalPort {
            get {
                return ((string)(this["TriggerDigitalPort"]));
            }
            set {
                this["TriggerDigitalPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TriggerDigitalLine {
            get {
                return ((string)(this["TriggerDigitalLine"]));
            }
            set {
                this["TriggerDigitalLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EncoderDigitalDevice {
            get {
                return ((string)(this["EncoderDigitalDevice"]));
            }
            set {
                this["EncoderDigitalDevice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EncoderDigitalPort {
            get {
                return ((string)(this["EncoderDigitalPort"]));
            }
            set {
                this["EncoderDigitalPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EncoderDigitalLine {
            get {
                return ((string)(this["EncoderDigitalLine"]));
            }
            set {
                this["EncoderDigitalLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TriggerLineIO {
            get {
                return ((bool)(this["TriggerLineIO"]));
            }
            set {
                this["TriggerLineIO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PhaseLineIO {
            get {
                return ((bool)(this["PhaseLineIO"]));
            }
            set {
                this["PhaseLineIO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EncoderLineIO {
            get {
                return ((bool)(this["EncoderLineIO"]));
            }
            set {
                this["EncoderLineIO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PhaseLineTCP {
            get {
                return ((bool)(this["PhaseLineTCP"]));
            }
            set {
                this["PhaseLineTCP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PhaseLineTcpPort {
            get {
                return ((string)(this["PhaseLineTcpPort"]));
            }
            set {
                this["PhaseLineTcpPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PhaseLineTcpPhaseonMsg {
            get {
                return ((string)(this["PhaseLineTcpPhaseonMsg"]));
            }
            set {
                this["PhaseLineTcpPhaseonMsg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PhaseLineTcpPhaseoffMsg {
            get {
                return ((string)(this["PhaseLineTcpPhaseoffMsg"]));
            }
            set {
                this["PhaseLineTcpPhaseoffMsg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PhaseLineSerialPort {
            get {
                return ((string)(this["PhaseLineSerialPort"]));
            }
            set {
                this["PhaseLineSerialPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PhaseLineSerialPhaseonMsg {
            get {
                return ((string)(this["PhaseLineSerialPhaseonMsg"]));
            }
            set {
                this["PhaseLineSerialPhaseonMsg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PhaseLineSerialPhaseoffMsg {
            get {
                return ((string)(this["PhaseLineSerialPhaseoffMsg"]));
            }
            set {
                this["PhaseLineSerialPhaseoffMsg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PhaseLineSerial {
            get {
                return ((bool)(this["PhaseLineSerial"]));
            }
            set {
                this["PhaseLineSerial"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TriggerLineTCP {
            get {
                return ((bool)(this["TriggerLineTCP"]));
            }
            set {
                this["TriggerLineTCP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TriggerLineTcpPort {
            get {
                return ((string)(this["TriggerLineTcpPort"]));
            }
            set {
                this["TriggerLineTcpPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TriggerLineTcpTriggerMsg {
            get {
                return ((string)(this["TriggerLineTcpTriggerMsg"]));
            }
            set {
                this["TriggerLineTcpTriggerMsg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TriggerLineSerialPort {
            get {
                return ((string)(this["TriggerLineSerialPort"]));
            }
            set {
                this["TriggerLineSerialPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TriggerLineSerialTriggerMsg {
            get {
                return ((string)(this["TriggerLineSerialTriggerMsg"]));
            }
            set {
                this["TriggerLineSerialTriggerMsg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TriggerLineSerial {
            get {
                return ((bool)(this["TriggerLineSerial"]));
            }
            set {
                this["TriggerLineSerial"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Logger_EnableLogging {
            get {
                return ((bool)(this["Logger_EnableLogging"]));
            }
            set {
                this["Logger_EnableLogging"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Logger_LoggingFolder {
            get {
                return ((string)(this["Logger_LoggingFolder"]));
            }
            set {
                this["Logger_LoggingFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Logger_AppendLogs {
            get {
                return ((bool)(this["Logger_AppendLogs"]));
            }
            set {
                this["Logger_AppendLogs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Logger_SplitLogFile {
            get {
                return ((bool)(this["Logger_SplitLogFile"]));
            }
            set {
                this["Logger_SplitLogFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int Logger_SplitMaxSize {
            get {
                return ((int)(this["Logger_SplitMaxSize"]));
            }
            set {
                this["Logger_SplitMaxSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TestMatrixLog.txt")]
        public string Logger_LogFileName {
            get {
                return ((string)(this["Logger_LogFileName"]));
            }
            set {
                this["Logger_LogFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GenerateProtocolIndex {
            get {
                return ((bool)(this["GenerateProtocolIndex"]));
            }
            set {
                this["GenerateProtocolIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ProtocolIndexLineSerial {
            get {
                return ((bool)(this["ProtocolIndexLineSerial"]));
            }
            set {
                this["ProtocolIndexLineSerial"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ProtocolIndexLineTCP {
            get {
                return ((bool)(this["ProtocolIndexLineTCP"]));
            }
            set {
                this["ProtocolIndexLineTCP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("51236")]
        public string ProtocolIndexLineTcpPort {
            get {
                return ((string)(this["ProtocolIndexLineTcpPort"]));
            }
            set {
                this["ProtocolIndexLineTcpPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("myindex")]
        public string ProtocolIndexMessage {
            get {
                return ((string)(this["ProtocolIndexMessage"]));
            }
            set {
                this["ProtocolIndexMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ProtocolIndexLineSerialPort {
            get {
                return ((string)(this["ProtocolIndexLineSerialPort"]));
            }
            set {
                this["ProtocolIndexLineSerialPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GenerateFixedTimingProtocolIndex {
            get {
                return ((bool)(this["GenerateFixedTimingProtocolIndex"]));
            }
            set {
                this["GenerateFixedTimingProtocolIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string ProtocolIndexFixedDelay {
            get {
                return ((string)(this["ProtocolIndexFixedDelay"]));
            }
            set {
                this["ProtocolIndexFixedDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string ProtocolIndexRandomMinDelay {
            get {
                return ((string)(this["ProtocolIndexRandomMinDelay"]));
            }
            set {
                this["ProtocolIndexRandomMinDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string ProtocolIndexRandomMaxDelay {
            get {
                return ((string)(this["ProtocolIndexRandomMaxDelay"]));
            }
            set {
                this["ProtocolIndexRandomMaxDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string ProtocolIndexCounterStartsFrom {
            get {
                return ((string)(this["ProtocolIndexCounterStartsFrom"]));
            }
            set {
                this["ProtocolIndexCounterStartsFrom"] = value;
            }
        }
    }
}
